const config = {
  openHour: 8,
  closeHour: 22,
  openHourString: "08:00:00",
  closeHourString: "22:00:00",
  openHourUTC: 7,
  closeHourUTC: 21,
  workingDayLengthInHours: 14,
  defaultReservationLength: 60,
  availableReservationLengths: [60, 90, 120],
  availableWeekdays: {
    0: "sunday",
    1: "monday",
    2: "tuesday",
    3: "wednesday",
    4: "thursday",
    5: "friday",
    6: "saturday",
    // monday: 1,
    // tuesday: 2,
    // wednesday: 3,
    // thursday: 4,
    // friday: 5,
    // saturday: 6,
  },
  minPasswordLength: 8,
  maxPasswordLength: 30,
  minUsernameLength: 5,
  maxUsernameLength: 20,
};

export default config;
